server.port: 8080
server.host: 0.0.0.0

wls-username: admin
wls-password: admin0000
wls-admin-url: t3://localhost:7001

mp:
  messaging:
    connector:
      helidon-jms:
        jndi:
          jms-factory: jms/TestConnectionFactory
          env-properties:
            java.naming.factory.initial: weblogic.jndi.WLInitialContextFactory
            java.naming.provider.url: ${wls-admin-url}
            java.naming.security.principal: ${wls-username}
            java.naming.security.credentials: ${wls-password}
    incoming:
      from-wls-1:
        connector: helidon-jms
        destination: ./TestJMSMOdule!TestReceiveQueue
    outgoing:
      to-wls-1:
        connector: helidon-jms
        destination: ./TestJMSMOdule!TestJMSQueue
      to-wls-2:
        connector: helidon-jms
        destination: ./TestJMSMOdule!TestJMSQueue-2
